### PR TITLE
#162163163 API documentation using swagger

### PR DESCRIPTION
**Pull request by lindseyme**
### What does this PR do?
This Pull Request documents API using swagger.

### Description of Task to be completed?
The existing API of the project have been documented using swagger. 

### How should this be manually tested?
Install swagger 

- pip install django-rest-swagger

Start the server and put the swagger url in the browser.

- api/swagger/

### What are the relevant pivotal tracker stories?
[#162163163](https://www.pivotaltracker.com/story/show/162163163)

### CODE REVIEW

**Review by mulondo — APPROVED** [review]

**Review by ongebo — APPROVED** [review]
Looks good to me

**Review by ekumamait — APPROVED** [review]

**Review by barema4 — APPROVED** [review]
looks nice

**Review by sekayasin — APPROVED** [review]
Good use of GenericAPIView, Approved

**Review by alexkayabula — APPROVED** [review]
Excellent documentation.

**Pull request merged**
