### PR TITLE
#162163175 User should be able to favourite and unfavourite articles.

### PR DESCRIPTION
**Pull request by mulondo**
### What does this PR do?
Favourite and unfavourite an article. 

### Description of the task to be completed?
* Logged in user can favorite and or unfavorite articles.

### How should this be manually tested?
* Send a put request to /api/users/article/favorite/slug  of any while logged in to favorite an article.
* Send a put request to /api/users/article/favorite/slug for an already favorited article unfavorites the article.

### What are the relevant pivotal tracker stories?
[#162163175](https://www.pivotaltracker.com/story/show/162163175)

### CODE REVIEW

**Review by alexkayabula — APPROVED** [review]
Looks good to me

**Review by ekumamait — COMMENTED** [review]
Refactor this
screen shot 2018-12-15 at 8 40 09 pm

**Comment by mulondo** [comment]
@ekumamait I have resolved it.

**Review by ekumamait — APPROVED** [review]
Looks good to me

**Review by sekayasin — APPROVED** [review]
Bravo, nice work

**Review by ongebo — APPROVED** [review]

**Pull request merged**
