### PR TITLE
#162163171 Add feature to enable logged in users to rate articles

### PR DESCRIPTION
**Pull request by ongebo**
### What does this PR do?
Adds a functionality that enables registered users to rate articles
#### Description of task to be completed?
- Add Rating model to articles app
- Add serializer for the Rating model
- Add API view to rate articles
- Write tests for implemented code
#### How should this be manually tested?
- Get all articles to expose their slugs (GET /api/articles/)
- Rate an article by copying its slug and hitting the endpoint: POST /api/articles/\<slug\>/ratings/
  - The POST data should have the format: {'rating': \<score\>}
  - \<score\> must be a number from 1 to 5
- GET /api/articles/ to verify that the article's rating has been modified
#### What are the relevant pivotal tracker stories
[#162163171](https://www.pivotaltracker.com/n/projects/2227671/stories/162163171)

### CODE REVIEW

**Review by lindseyme — APPROVED** [review]

**Review by ekumamait — APPROVED** [review]
Looks good to merge

**Review by sekayasin — APPROVED** [review]
nice work

**Review by barema4 — APPROVED** [review]
good work

**Review by mulondo — APPROVED** [review]
good job

**Pull request merged**
