### PR TITLE
#162163182 Allow authenticated users to share articles 

### PR DESCRIPTION
**Pull request by lindseyme**
### What does this PR do?
Add functionality for authenticated users to be able to share articles across social media and using email. 
#### Description of the task to be completed
- Create classes in the article view for social media sharing and using emails for sharing.
- Write tests for the social share views.
#### How should this be manually tested?
- Get all articles.
- Get the article slug.
- To share via email: POST / api/articles/\<slug\>/email/
- To share via twitter: POST api/articles/\<slug\>/twitter/
- To share via facebook: POST api/articles/\<slug\>/facebook/
#### What are the relevant pivotal tracker stories?
[#162163182](https://www.pivotaltracker.com/story/show/162163182)

### CODE REVIEW

**Review by alexkayabula — APPROVED** [review]
Looks good to me.

**Review by sekayasin — APPROVED** [review]
nice work.

**Review by ongebo — APPROVED** [review]
Nice work.

**Review by mulondo — APPROVED** [review]
good job

**Review by barema4 — APPROVED** [review]
Nice work

**Pull request merged**
