### PR TITLE
#162163161 Setup and deploy base application to Heroku

### PR DESCRIPTION
**Pull request by sekayasin**
### What does this PR do?
Setup and deploy the base application to heroku
#### How should this be manually tested?
- Test the staging app on heroku [here](https://zeus-staging-app.herokuapp.com/admin)
-  For testing, user these default admin credentials 
    - email: zeus@example.com
    - password: zeus@admin 
#### Any background context you want to provide?
Heroku has a free tier which is good for our hosting requirements
#### What are the relevant pivotal tracker stories?
[#162163161](https://www.pivotaltracker.com/story/show/162163161)
#### Screenshots (if appropriate)
zeus-django-heroku

### CODE REVIEW

**Review by alexkayabula — APPROVED** [review]
Nice work.

**Review by ongebo — APPROVED** [review]
Good work making the builds pass

**Review by ekumamait — APPROVED** [review]
Kudos Yasin

**Review by mulondo — APPROVED** [review]

**Review by barema4 — APPROVED** [review]
looks nice

**Pull request merged**
