### PR TITLE
#162163164 Users should receive a JWT on successful Registration

### PR DESCRIPTION
**Pull request by ekumamait**
**What does this PR do?**
Generates a JSON Web Token after a user has provided the correct credentials during registration or login. 
**Description of Task to be completed?**
* Adds user token generation functionality
* Adds Authorization functionality
* Adds a tests module
* Adds tests for authentication

**How should this be manually tested?**
* Open POSTMAN, add the link /api/users/ to the localhost url to register a new user.
* Provide the body format for registration from the documentation { "user":{ "username": "Jacob", "email": "jake@jake.jake", "password": "jakejake" } } 
User should be able to receive a JSON Web Token after both registration and login.

**What are the relevant pivotal tracker stories?** 
#16216316

Screenshots (if appropriate)
screen shot 2018-12-03 at 3 17 32 pm

### CODE REVIEW

**Review by alexkayabula — APPROVED** [review]
Nice implementation.

**Review by sekayasin — APPROVED** [review]
Approved! Good use of docstrings

**Review by barema4 — APPROVED** [review]
Good work

**Review by ongebo — APPROVED** [review]
Looks good to me

**Pull request merged**
