### PR TITLE
 #162163162 Integrate Coveralls Code Coverage Service

### PR DESCRIPTION
**Pull request by barema4**
### What does this PR do?
 

- Shows the percentage of code that has been tested

### Description of the task to be completed

- Creating .coverage.yml file
- Updating README.md file to include coverage badge

### How should this be manually tested

- Install coveralls through pip install coveralls
- Include coveralls in requirements.txt file

### What are the relevant pivotal tracker stories?
[#162163162](https://www.pivotaltracker.com/story/show/162163162)

### CODE REVIEW

**Review by alexkayabula — APPROVED** [review]
Nice work @barema4.

**Review by sekayasin — COMMENTED** [review]
@barema4 This looks good, now Let's try to Squash commits

**Review by lindseyme — APPROVED** [review]
Looks good to me

**Review by mulondo — APPROVED** [review]

**Review by sekayasin — APPROVED** [review]
@barema4 nice work, Approved

**Review by ongebo — APPROVED** [review]
Seems to be fine

**Review by ekumamait — APPROVED** [review]
Good job sam.

**Comment by barema4** [comment]
closed

**Pull request closed without merging**
