### PR TITLE
#162163172 Users should be able to comment on articles

### PR DESCRIPTION
**Pull request by barema4**
### What does this PR do?
it helps users to comment on the articles posted 
### Description of Task to be completed?
- create models for comments and replies
- Ensure that the  endpoints work very well
### How should this be manually tested?
- install requirements by pip install requirements.txt
- create a database and run migrations
- run the server by python manage.py runserver
- run the following endpoints
  - POST /api/\<slug\>/comments/
  - GET /api/\<slug\>/comments/
  - PUT /api/comment/\<commentID\>/
  - DELETE /api/comment/\<commentID\>/
  - POST /api/comment/\<commentID\>/replies/
  - PUT  /api/comment/replies/\<replyID\>/
  - DELETE /api/comment/replies/\<replyID\>/
### What are the relevant pivotal tracker stories?
[#162163172](https://www.pivotaltracker.com/story/show/162163172)

### CODE REVIEW

**Review by alexkayabula — APPROVED** [review]
Looks good to me.

**Review by ongebo — APPROVED** [review]
Nice work!

**Review by lindseyme — APPROVED** [review]
Good work

**Review by sekayasin — APPROVED** [review]
nice work

**Review by ekumamait — APPROVED** [review]

**Pull request merged**
