### PR TITLE
#162163170 create, retrieve, update and destroy articles:

### PR DESCRIPTION
**Pull request by ekumamait**
**What does this PR do?**
This Pull Request creates an app called articles where:
	•	Authors can create articles
	•	Authors can view articles
	•	Authors can only edit articles they created
	•	Authors can only delete articles they created

**Description of Task to be completed?**
Currently, users can only register and create profiles.
This task creates an articles app in the codebase that will help those users create articles, fetch and update the articles.

**How should this be manually tested?**
	•	Make migrations: `./manage.py make migrations articles`
	•	Migrate: `./manage.py migrate`
	•	Run the server: `./manage.py runserver`
	•	Open postman and test the endpoints:

**Create an article** 
POST `http://127.0.0.1:8000/api/articles/ Body:`
```
{
  "article": {
    	"title": "How to train your dragon",
    "description": "Ever wonder how?",
    "body": "It takes a Jacobian"
	}
}

```
**Get all articles** 
GET `http://127.0.0.1:8000/api/articles/`

**Get specific article (not authenticated)** 
GET `http://127.0.0.1:8000/api/articles/<slug>/`

**Edit article**
 PUT `http://127.0.0.1:8000/api/articles/<slug>/ `
body:
```
{
  "article": {
    	"title": "How to train your dragon",
    "description": "Ever wonder how?",
    "body": "It takes a Astrid”
	}
}

```
**Delete article** 
DELETE `http://127.0.0.1:8000/api/articles/<slug>/`

**What are the relevant pivotal tracker stories?**
[#162163170](https://www.pivotaltracker.com/story/show/162163170)

**Any background context you want to add?**
Since we are generating a random slug, use that to search for a specific article you’re trying to find

**Screenshots (if appropriate)**
Creating an article:
screen shot 2018-12-11 at 6 23 44 pm

To fetch all created articles:
screen shot 2018-12-11 at 7 00 53 pm

To fetch a specific article:
screen shot 2018-12-11 at 7 01 37 pm

Co-authored-by: mulondo moses <mulondo26@gmail.com>

### CODE REVIEW

**Review by ongebo — APPROVED** [review]
Nice work!

**Review by mulondo — APPROVED** [review]

**Review by sekayasin — APPROVED** [review]
nice work +1

**Review by barema4 — APPROVED** [review]
Nice work

**Review by lindseyme — APPROVED** [review]

**Comment by alexkayabula** [comment]
Nice Work

**Pull request merged**
