### PR TITLE
#162163184 Users should be able to report an article

### PR DESCRIPTION
**Pull request by alexkayabula**
## What does this PR do?
- The PR adds a feature that enables users to report articles that violate terms and agreements.
### Description of task to be completed?
- A user must specify the reason for reporting the article.
### How should this be manually tested?
- Use the following endpoint 
```
POST http://localhost:8000/api/<slug>/report_article

{"reason" : "This article contains plagiarized material from Andela.com"}
```
### What are the relevant pivotal tracker stories?
[#162163184](https://www.pivotaltracker.com/story/show/162163184)

### CODE REVIEW

**Review by sekayasin — APPROVED** [review]
nice work

**Review by barema4 — APPROVED** [review]
Nice work

**Review by ekumamait — APPROVED** [review]
LGTM

**Review by lindseyme — APPROVED** [review]
looks good

**Pull request merged**
