### PR TITLE
#162163153 Write Tests for existing project functionality

### PR DESCRIPTION
**Pull request by lindseyme**
### What does this PR do?
This Pull Request adds tests to the already existing functionality

### Description of Task to be completed?
Tests for the existing functionality which is log in and registration of a user have been added to the code base.

### How should this be manually tested?
- Clone the repository and cd into the folder.
- Run the following commands;
   - pip install -r requirements.txt
   - python manage.py test
- To view coverage, run the following commands;
   - pip install coverage
   - coverage run --source='authors' manage.py test
   - coverage report

### What are the relevant pivotal tracker stories?
[#162163153](https://www.pivotaltracker.com/story/show/162163153)

### CODE REVIEW

**Review by mulondo — APPROVED** [review]
this is fine

**Review by barema4 — CHANGES_REQUESTED** [review]
Nice work but change the title of PR to start with the story ID

**Review by barema4 — APPROVED** [review]

**Review by alexkayabula — APPROVED** [review]
The tests are very precise. Good work.

**Comment by ongebo** [comment]
It's good that the tests are running. Perhaps you should have squashed the commits into one, checkout this resource: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Review by sekayasin — COMMENTED** [review]
@lindseyme this looks good, let's try to squash commits.

**Review by sekayasin — APPROVED** [review]
@lindseyme Awesome with the squash, Approved

**Review by ongebo — APPROVED** [review]
Good work squashing the commits

**Pull request merged**
