### PR TITLE
#162163155 Upgrade Authors Haven Django app from Django 1.10 to Django 2.1

### PR DESCRIPTION
**Pull request by ekumamait**
**What does this PR do?**
Upgrades the codebase from Django 1.10 to Django 2.1

**Description of Task to be completed?**
- Update project requirements
- Refactor urls to format used by Django 2.1

**How should this be manually tested?**
- install project requirements using `pip install -r requirements.txt`
- check for Django version

**What are the relevant pivotal tracker stories?**
[#162163155](https://www.pivotaltracker.com/story/show/162163155)

### CODE REVIEW

**Review by sekayasin — APPROVED** [review]
@ekumamait This looks good. In the project settings file. Kindly change the time zone to "Africa/Kampala".  I have Approved this.

**Review by barema4 — APPROVED** [review]
You have done well

**Review by alexkayabula — APPROVED** [review]
Good work.

**Review by mulondo — APPROVED** [review]
great

**Pull request merged**
