### PR TITLE
#162163179 Pagination functionality for articles

### PR DESCRIPTION
**Pull request by lindseyme**
### What does this PR do?
Adds pagination functionality for articles.
#### Description of task to be completed
- Create a pagination script with a class to customize the pagination defaults.
- Add the pagination class to the views.
#### How should this be manually tested?
- Get all articles.
- Verify that there are ten articles per page with the next and previous links.
#### What are the relevant pivotal tracker stories?
[#162163179](https://www.pivotaltracker.com/story/show/162163179)

### CODE REVIEW

**Review by ongebo — APPROVED** [review]
Looks good to me.

**Review by alexkayabula — APPROVED** [review]
Looks ok

**Review by sekayasin — APPROVED** [review]
nice work

**Review by barema4 — APPROVED** [review]
Nice work

**Pull request merged**
