### PR TITLE
#162163177 Add functionality to list all users and their profiles

### PR DESCRIPTION
**Pull request by ongebo**
## What does this PR do?
It adds a feature that enables a logged in user to see a list and profiles of all registered authors
### Description of task to be completed?
* Add API endpoint to return a list of all authors and their profiles
* Add authentication to the endpoint (only logged in users allowed)
* Write tests for the added endpoint
### How should this be manually tested?
* Clone this repository and checkout the branch: 'ft-list-users-and-profiles-162163177'
* Setup project database (make and apply migrations)
* Register some users using Postman
* Retrieve all users with Postman by hitting the endpoint: GET /api/authors/
* Verify that the users have been returned
### What are the relevant pivotal tracker stories?
[#162163177](https://www.pivotaltracker.com/n/projects/2227671/stories/162163177)

### CODE REVIEW

**Review by alexkayabula — APPROVED** [review]
Good work.

**Review by sekayasin — APPROVED** [review]
Bravo!

**Review by barema4 — APPROVED** [review]
looks nice

**Review by barema4 — APPROVED** [review]
looks nice

**Review by lindseyme — APPROVED** [review]
Looks good to me

**Pull request merged**
