### PR TITLE
#162163169 Users should be able to create their profiles

### PR DESCRIPTION
**Pull request by mulondo**
### What does this PR do?
It creates a user profile after the user has registered.

### Description of the task to be completed?
* The user profile is created immediately after the user has registered. 
* When the user profile is created, the bio, image and fun_fact fields are set to be black by default.
* The user can log in and update their user profile.

### How should this be manually tested?
* clone the repository
* type in the terminal "pip install -r requirements.txt" to install the requirements on your local machine.
* git checkout ft-create-userprofile-#162163169.
* make migrations
* run the server and test out the endpoints in postman.

### What are the relevant pivotal tracker stories?
[#162163169](https://www.pivotaltracker.com/story/show/162163169)

### CODE REVIEW

**Review by barema4 — APPROVED** [review]
Nice work

**Review by alexkayabula — APPROVED** [review]
Good work.

**Review by sekayasin — APPROVED** [review]
looks good! Approved

**Review by ekumamait — APPROVED** [review]
Looks good to merge.

**Pull request closed without merging**
