### PR TITLE
#162163167 Password Reset Link for Users

### PR DESCRIPTION
**Pull request by sekayasin**
### What does this PR do?
The PR adds a password reset functionality to enable users to reset their password via email
#### Description of Task to be completed?
A user is required to provide his/her valid author's haven registered email  and a password reset link is sent to that email
#### How should this be manually tested?
This endpoint below is used for password reset

`POST http://localhost:8000/api/users/password_reset/`

enter json

`{"user":{"email": "sekayasin@yahoo.com"}}`

When a user clicks on the password reset link, he/she will be required to enter a new password

#### Any background context you want to provide?
- We used the Google's GMAIL SMTP Relay services compared to other SMTP Relay providers because of it was simple to configure and faster. 
#### What are the relevant pivotal tracker stories?
 [#162163167](https://www.pivotaltracker.com/story/show/162163167)

### CODE REVIEW

**Review by alexkayabula — APPROVED** [review]
Looks good to me.

**Review by barema4 — APPROVED** [review]
Nice work

**Review by ekumamait — APPROVED** [review]
looks good to merge

**Review by lindseyme — APPROVED** [review]
Looks good to me

**Pull request merged**
