### PR TITLE
 #162163178 Users should be able to tag their articles

### PR DESCRIPTION
**Pull request by sekayasin**
### What does this PR do?
The PR Adds functionality to enable authors to tag their articles
#### How should this be manually tested?
During article creation, the user will be able to tag his/her article

Article Creation
```
POST http://localhost:8000/api/articles/
{
	"article": {
		"title": "Blog Like a Pro",
		"description": "Sam's introduction to blogging in 24hrs - PacktPub",
		"body": "Blogger is awesome, as a blogger, you write 24/7, Really!",
		"tagList": ["blogger, "PacktPub", "Pro"],
		"images": ["http://zeus.com/awsome_me.png"]
	}
}
```

#### What are the relevant pivotal tracker stories?
 [#162163178](https://www.pivotaltracker.com/story/show/162163178)

### CODE REVIEW

**Review by ekumamait — APPROVED** [review]
LQTM apart from failing coveralls check

**Review by barema4 — APPROVED** [review]
Nice work

**Review by alexkayabula — APPROVED** [review]
Looks ok

**Review by lindseyme — APPROVED** [review]
Looks fine

**Comment by inno-asiimwe** [comment]
Resolve conflicts @sekayasin

**Pull request merged**
