### PR TITLE
#163357225 Fix social login with Facebook and Google

### PR DESCRIPTION
**Pull request by alexkayabula**
## What does this PR do?
- The PR ensures that the ```Internal server error 500``` error when social users login with previously registered emails is fixed.
### Description of task to be completed?
- Social users logging in with previously registered emails would receive an internal error 500 when logging in. Since the application does not allow duplicate emails and the exception wasn't handled earlier, the error persisted.
- To handle the bug, an exception has been created in that when a user logs in with an already registered email, an error message is returned and the application doesn't crash.
### How should this be manually tested?
- Clone the repository.
- Install the requirements ```pip install -r requirements.txt```
- Access the social login routes using Postman.
screen shot 2019-01-21 at 12 34 28
screen shot 2019-01-21 at 12 35 07

### What are the relevant pivotal tracker stories?
[#163357225](https://www.pivotaltracker.com/story/show/163357225)

### CODE REVIEW

**Comment by inno-asiimwe** [comment]
@alexkayabula Description for this `PR` is not clear. What was the cause of the error and how was it resolved? Can we have this information is the description.

**Comment by alexkayabula** [comment]
> @alexkayabula Description for this `PR` is not clear. What was the cause of the error and how was it resolved? Can we have this information is the description.

I have edited the description.

**Review by ekumamait — APPROVED** [review]

**Review by sekayasin — APPROVED** [review]
@alexkayabula Bravo, LGTM

**Review by barema4 — APPROVED** [review]
Nice fix for the bug

**Pull request merged**
